---
- name: install packages
  apt:
    name: tzdata
    update_cache: true
    cache_valid_time: 86400
  when: timezone_setup == "full"

- name: set timezone
  timezone:
    name: "{{ timezone_zone }}"
  when: timezone_zone | length > 0
